load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/c599e6a922a80e40e24a2d3c994a6dd51046796b.tar.gz",
    ],
    strip_prefix = "grpc-c599e6a922a80e40e24a2d3c994a6dd51046796b",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()
